M48
; DRILL file KiCad 10.0.0 date 2026-07-21T17:15:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-21T17:15:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X124.586Y-56.443
X124.586Y-79.057
X147.414Y-56.443
X147.414Y-79.057
T2
X150.0Y-109.0
M30
